### ISSUE TITLE
Multithreading Adapters not working after version 2.1.0

### ISSUE THREAD

**Issue by mathijspieters** [Adapter-Hub/adapter-transformers#258]
## Environment info
- `adapter-transformers` version: 2.2.0
- Platform: macOS-10.14.6-x86_64-i386-64bit
- Python version: 3.8.5
- PyTorch version (GPU?): 1.10.0 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: yes

## Details
Hi there! I'm trying to use Adapters in a multithreaded environment. Unfortunately, the predictions seem to be incorrect when using multiple threads where each thread might use a different adapter. 

In [this](https://github.com/Adapter-Hub/adapter-transformers/issues/165) issue this problem is already discussed, and as of version `v2.0.1` the functionality was restored. However, in the latest release, `v2.2.0` this seems again to be not working. I've verified that in release `v2.1.0` multithreading was however still working.

The script that I used is as follows:

```python
from transformers import AutoModelWithHeads, AdapterConfig
from transformers import AutoTokenizer
import torch
from torch.multiprocessing import Lock
from torch.nn import Softmax

N = 10
lock = Lock()

def perform_lock(model, adapter, tokenized, actual):
    errors = 0
    for i in range(N):
        with lock:
            pred = model.forward(**tokenized, adapter_names=adapter)
            predicted = softmax(pred[0])[0,1]
        try:
            assert torch.isclose(predicted, actual),  f"{adapter}:{i}: {predicted} is not {actual}"
        except Exception:
            errors += 1
    print(f"  Lock {adapter:<8} failed {errors} times")

def perform_no_lock(model, adapter, tokenized, actual):
    errors = 0 
    for i in range(N):
        pred = model.forward(**tokenized, adapter_names=adapter)
        predicted = softmax(pred[0])[0,1]
        try:
            assert torch.isclose(predicted, actual),  f"{adapter}:{i}: {predicted} is not {actual}"
        except Exception:
            errors += 1
    print(f"NoLock {adapter:<8} failed {errors} times")

if __name__ == "__main__":
    model = AutoModelWithHeads.from_pretrained("distilbert-base-uncased")
    tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
    softmax = Softmax(dim=1)

    config = AdapterConfig.load("houlsby")
    houlsby = model.load_adapter("sentiment/sst-2@ukp", config=config, load_as="houlsby")

    config = AdapterConfig.load("pfeiffer")
    pfeiffer = model.load_adapter("sentiment/sst-2@ukp", config=config, load_as="pfeiffer")

    adapters = []
    tokenizeds = []
    expecteds = []

    for s in ["This is a test", "This is a completely different sentence that should give a different result", "Mooooore hate", "even more love"]:
        for a_name in [pfeiffer, houlsby]:
            tokenized = tokenizer(s, return_tensors='pt')
            pred = model.forward(**tokenized, adapter_names=a_name)
            actual = softmax(pred[0])[0,1]
            adapters.append(a_name)
            tokenizeds.append(tokenized)
            expecteds.append(actual)
    
    from threading import Thread
    t_locks = []
    for a, t, e in zip(adapters, tokenizeds, expecteds):
        t = Thread(target=perform_lock, args=(model, a, t, e))
        t_locks.append(t)

    for t in t_locks:
        t.start()

    for t in t_locks:
        t.join()

    t_no_lock = []
    for a, t, e in zip(adapters, tokenizeds, expecteds):
        t = Thread(target=perform_no_lock, args=(model, a, t, e))
        t_no_lock.append(t)

    for t in t_no_lock:
        t.start()

    for t in t_no_lock:
        t.join()
```

Is it possible to restore the functionality that supports multithreading with different adapters? Thanks a lot :)

**Comment by calpt** [comment]
Hey @mathijspieters,

Thanks a lot for the detailed description & code snippet. I've looked into you script a bit and I think this issue is not directly related to the multithreading functionality but rather a rather unintuitive difference between the `adapter_names` parameter and `set_active_adapters()`:

Unlike `set_active_adapters()`, the `adapter_names` parameter __only__ activates adapter modules, but **not** prediction heads that might together with an adapter. To activate a prediction head in a model forward pass with the `AutoModelWithHeads` model class, it is required to pass the `head` parameter, i.e. the forward call in you example should look like this to also activate the heads:
```python
pred = model.forward(**tokenized, adapter_names=adapter, head=adapter)
```
Now, your script should work as intended.

Why does the shown example still work prior to v2.2.0? In earlier versions, the `load_adapter()` method automatically activated prediction heads it loaded. Therefore, the head of the adapter loaded will be set as active prediction head. As this is not overwritten afterwards (e.g. no `head` parameter is passed), it will __always__ use this same prediction head, no matter of the adapter activated with `adapter_names`. This has changed in v2.2.0 where you would have to pass `set_active=True` to activate both the adapter and head.

You can verify this behavior by printing `model.active_head` after the second `model.load_adapter()`, Pre v2.2.0, it will show the second head as active, afterwards none. When ensuring that no head is active by setting `model.active_head = None` after adapter loading, you can also verify that indeed no prediction head is used in the forward pass by printing `pred[0].shape` afterwards.

Hope this helps!

(As a side note, we again plan to make changes to the `adapter_names` parameter while keeping the multi-threading functionality. Please have a look at #257).

**Comment by mathijspieters** [comment]
Hi @calpt! 

Thanks a lot for your very detailed explanation! I've tested your suggestion, and it indeed works as expected 🙏 

The context manager you mentioned looks really cool, and I really like where you are going with this project.

Keep up the good work 💪💪
