### ISSUE TITLE
Train BART with adapters in generation task but can't retrieve prefix states from context

### ISSUE THREAD

**Issue by tingyaohsu** [adapter-hub/adapter-transformers#348]
Hi, I tried to train adapter with BART in generation task following the [Docs](https://adapterhub.ml/).
There was nothing inside the context when I used the prefix tuning. I have searched, but not found similar issues that I encountered so far.

Here is shortcut of my training script.

```
from transformers.adapters import MAMConfig
 
model = BartForConditionalGeneration.from_pretrained('sshleifer/distilbart-cnn-12-6')
config = MAMConfig()
model.add_adapter("mam_adapter", config=config)
model.train_adapter("mam_adapter")
model.set_active_adapters("mam_adapter")
```

When I tried to train the model and it showed the errors.

```
KeyError  Traceback (most recent call last)

....
....

.../lib/python3.6/site-packages/transformers/adapters/prefix_tuning.py in forward(self, key_states, value_states, attention_mask, invert_mask)
prefix_keys, prefix_values = context.prefix_states[prefix_tuning_name][self.location_key][prefix_id ]

KeyError: 'mam_adapter'
```

I printed out the context after `ForwardContext.get_context()` but get nothing. What suppose to get from the context? 

I can provide more details if needed, thanks !

**Comment by calpt** [comment]
Hey @tingyaohsu, thanks for reporting this. Would you mind providing a complete code snippet that reproduces the issue you mentioned? This makes it a lot easier for us to address the issue. Thanks!

**Comment by LZY-the-boys** [comment]
> Hey @tingyaohsu, thanks for reporting this. Would you mind providing a complete code snippet that reproduces the issue you mentioned? This makes it a lot easier for us to address the issue. Thanks!

I also have this issue when I use mam and prefix-tuning in T5 and simply get the same error as above. This is because this `context.prefix_states` is None in model generating . 

 I view the source code and notice that when training, the transformers forward is `T5ConditionalGeneration.forward()` which has a `@ForwardContext.wrap` wrapper pre-computes the `context.prefix_states` so it's normal. However when generating the `model.generate()` will first call `model.encoder.forward()`(which is `T5Stack`) to get the encoder_output and call `model.decoder.forward()` multiple times to autoregressively generate and **the `T5Stack` has no `@ForwardContext.wrap` wrapper so  `context.prefix_states` is None! **

**Comment by calpt** [comment]
@LZY-the-boys thanks for adding your findings to this. While what you describe is correct, I believe it still should be possible to use the generate() method together with Prefix Tuning in the latest version. I just checked the example scripts and couldn't reproduce this issue. We also have a test that should cover generation with prefix tuning (which passes for both BART and T5):
https://github.com/adapter-hub/adapter-transformers/blob/8440ab4ffc10b17e2c29c7fc8592190090c50ab7/tests_adapters/methods/test_prefix_tuning.py#L58-L80
Please add some further steps to help us reproduce this issue, thanks!

**Comment by LZY-the-boys** [comment]
@calpt OK, I have just tried this code and it works because for generating the `_prepare_encoder_decoder_kwargs_for_generation` function calling the encoder has `with ForwardContext(self, **encoder_kwargs)` in it, which is different from old transformers's code. Before this, I customized this function for special use so it crashed. Thanks for help!

I have to say, the transformers' package code has became much complex :( . I didn't expect the generation code has changed when adding adapters.

**Comment by RealNicolasBourbaki** [comment]
Hi @LZY-the-boys, thanks for your helpful comment here! Just one question: after I manually added ```@ForwardContext.wrap``` to my customized ```generate``` function, I got ``` 'MultimodalConfig' object has no attribute 'adapters'``` error. MultimodalConfig is also customized. How come so? I checked out BERTConfig and such and none of them has ```adapters``` attribute.
