### ISSUE TITLE
load adapter

### ISSUE THREAD

**Issue by jbgruenwald** [adapter-hub/adapter-transformers#353]
I have trained an adapter and saved it to my hard drive.

When I want to load it, I use the following code:
```
adapter_name = model.model.roberta.load_adapter(adapter_path, set_active=True)
print(model.model.roberta.active_adapters)
```

But I get the following errors:
```
/home/some-path/some-python-script.py:255: UserWarning: use_multiprocessing automatically disabled as xlmroberta fails when using multiprocessing for feature conversion.
  warnings.warn(
Overwriting existing adapter 'adapter-name'.
None
 Converting to features started. Cache is not used.
100%|██████████| 2000/2000 [00:00<00:00, 3960.89it/s]
  0%|          | 0/250 [00:00<?, ?it/s]There are adapters available but none are activated for the forward pass.
  0%|          | 1/250 [00:00<01:19,  3.11it/s]There are adapters available but none are activated for the forward pass.
  1%|          | 2/250 [00:00<01:12,  3.44it/s]There are adapters available but none are activated for the forward pass.
```

Why does it say None immediately after I set it active?

If I set it active with `set_active_adapter(adapter_name)`, it says that it couldn't find an adapter with that name, even immediately after loading the adapter, but when doing the forward action it still says `There are adapters available but none are activated for the forward pass.`

Is there an function that to gives me the list of loaded adapters?

**Comment by calpt** [comment]
Hey @jbgruenwald,

The behavior you report does not look expected. From looking at the code you provided, there could be an issue when you don't call the `load_adapter()`/ `set_active_adapters()` methods on the top-level class, i.e. if "model" or "model.model" also is a built-in model class (RobertaForSequenceClassification, RobertaAdapterModel etc.), you should call all adapter methods on this instance instead of "model.model.roberta". If this is not the case, it would helpful if you could provide some additional context on your setup so we can have a look at this.

> Is there an function that to gives me the list of loaded adapters?

Yes, each loaded adapter adds its config to the model config, so you should be able to access all loaded adapters with `model.model.roberta.config.adapters.adapters`
