### ISSUE TITLE
Error in loading datasets?

### ISSUE THREAD

**Issue by cws7777** [adapter-hub/adapter-transformers#362]
## Environment info

     
- `adapter-transformers` version: Newest
- Platform: Ubuntu 18.04
- Python version: 3.6
- PyTorch version (GPU?): 1.10.2+cu102

## Details
Hi, It didn't give me an error like below when I use regular `[Trainer](https://huggingface.co/docs/transformers/main_classes/trainer)` from transformers, but occurs  the error when I use `transformers.AdapterTrainer`,
![image](https://user-images.githubusercontent.com/12144129/172350673-d332e788-103a-4245-90ff-ce9c6004347e.png)

In my opinion, the dataset that I'm using is a bit different with common dataset that is using in Adapter-transformer, but just guessing..
Any help...??

Thanks..!

**Comment by calpt** [comment]
Hey @cws7777, from the stack trace you provided, your issue seems to be related to the adapter setup you're providing via `adapter_names` parameter of the `AdapterTrainer` class. Could you provide the value (if any) you're passing to this parameter when creating the trainer class so we can have a look? Thanks!

**Comment by adapter-hub-bert** [comment]
This issue was closed because it was stale for 14 days without any activity.
