### ISSUE TITLE
Query regarding adapter type

### ISSUE THREAD

**Issue by prajjwal1** [Adapter-Hub/adapter-transformers#39]
Thanks for this project. I had a query which has not been discussed in the docs. I wanted to ask when we use `run_glue.py` example from this repo, which type of adapter is added.
1. Is the type same as Fig 2 (right) (two feed-forward layers up and down) or is it different ?
2. When we use the above script, do we use `AdapterFusion` method by default ?

**Comment by JoPfeiff** [comment]
Our current architecture implementations always include a down and up projection. `houlsby` has two in each layer, `pfeiffer` has one in each layer. 
There is a sample script of AdapterFusion for glue:
https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/text-classification/run_fusion_glue.py
however, by setting 
https://github.com/Adapter-Hub/adapter-transformers/blob/0db6d5d406fb93507bc412e798c11bff8f4a6827/examples/text-classification/run_fusion_glue.py#L200
to 
`model.add_fusion(adapter_names[0], "dynamic", {"regularization": True})`
you might get better results. 
We are currently working on some colab scripts to make this easier to understand. 
Also please refer to the description of the last major PR where I have briefly described how to stack and fuse:
https://github.com/Adapter-Hub/adapter-transformers/pull/22

We will include more documentation regarding this in the upcoming days

**Comment by prajjwal1** [comment]
Here's what I can infer from your reply. Sorry I'm not completely familiar with adapter-transformer codebase. 

1. Yes, I saw that you've mentioned in the paper "finding that a two-layer feed-foward neural network with a bottleneck works well". But your implementation uses Fig 2 (right) architecture from your paper right ? By two FFN, you mean 4 linear layers (up and down) or 2 linear layers (up and down). 

2. AdapterFusion is not used if we use this example right ? 
[run_glue.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/text-classification/run_glue.py). How adapters are being used here, is it the standard way as proposed in Houlsby et al.?

 If not, if you can provide a brief description, that'd be helpful.

**Comment by JoPfeiff** [comment]
1. you can chose which adapter you want. this one uses the `houlsby` architecture: https://adapterhub.ml/adapters/ukp/bert-base-uncased-mnli_houlsby/ and this one the `pfeiffer` architecture: https://adapterhub.ml/adapters/ukp/bert-base-uncased-mnli_pfeiffer/ AdapterFusion relies on pre-trained adapters, so you would want to leverage either.
2. you can train adapters or leverage pre-trained ones for AdapterFusion in any script with minimal changes. For now we only have Adapters directly implemented in the glue and NER scripts. We additionally give an example for Fusion here: https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/text-classification/run_fusion_glue.py

From our perspective it is too complex to implement AdapterFusion with CLI arguments because depending on your setting you would want to decide which adapters of a certain architecture, in a specific order, maybe include stacking, etc. That is why the `run_fusion_glue.py` script has a set of adapters **hard coded.** 
In order to try out fusion with other tasks and adapters please adjust the scripts manually, similarly to the `run_fusion_glue.py` script.

**Comment by prajjwal1** [comment]
Thanks for the additional info you've provided but it seems that my questions are not directly answered here. Can you please confirm once ?

1. Since I used `pfeiffer` config, I assume that my adaptor consisted of two Linear layers up and down. So  `pfeiffer` is the same as Figure 3 of your paper. Please correct me if I'm wrong.

2. This has been left unanswered. Does `run_glue.py` uses the same method as `houlsby` ?

**Comment by JoPfeiff** [comment]
1. yes
2. `run_glue.py` uses the adapter architecture which you define. you can set `--adapter_config pfeiffer` or `--adapter_config houlsby`. Both have a default `reduction_factor` of 16. default `pfeiffer` uses a `relu` activation function, default `houlsby` a `swish` activation function (https://github.com/Adapter-Hub/adapter-transformers/blob/0db6d5d406fb93507bc412e798c11bff8f4a6827/src/transformers/adapter_config.py#L120). you can redefine both with e.g. `adapter_config = AdapterConfig.load("houlsby", non_linearity="gelu", reduction_factor=2)` and then `.add_adapter(task_name, AdapterType.text_task, config=adapter_config)`

**Comment by prajjwal1** [comment]
Okay. Thanks for your answers.
So `run_glue.py` uses the same training strategy as `houlsby`, except we can define our architecture through `--adapter_config`. 

If I want to use `AdapterFusion` method, I may have to use https://github.com/Adapter-Hub/adapter-transformers/blob/master/examples/text-classification/run_fusion_glue.py which does performs the Fusion operation as mentioned in the paper.

I hope I'm correct. It would be nice to have this documented. Looking forward to more updates in the repo.

**Comment by prajjwal1** [comment]
Hi, this question is somewhat unrelated to this Adapters. I am trying to study adapters with my setup and I was trying to visualize attention similar to what you've done in Fig 5 of your paper. 

Could you please provide the relevant code you used for plotting or point me to the right place so that there is no discrepancy between what you showed and my implementation ?
