### ISSUE TITLE
Flexible Adapter Composition

### ISSUE THREAD

**Issue by SpaceHunterInf** [adapter-hub/adapter-transformers#475]
Greetings,

Suppose I have adapter A, B, C and a fusion layer Fuse(A,B,C). How could I freeze domain B, and train adapter A,C and fusion layer Fuse(A,B,C) only? Does the current version support such operation?

Thanks.

**Comment by SpaceHunterInf** [comment]
I've read the docs about composition, it's not quite what I want. Is there a method that I can deactivate an adapter easily?

**Comment by hSterz** [comment]
Hey @SpaceHunterInf, unfortunately this is not supported out of the box. In order to achieve this you need to implement something similar to the [`train_adapters` method](https://github.com/adapter-hub/adapter-transformers/blob/master/src/transformers/adapters/model_mixin.py#L322)  and the [`train_adapter_fusion` method](https://github.com/adapter-hub/adapter-transformers/blob/cffdf3974ea19f49e1febe6e3f5b74be4e2d496a/src/transformers/adapters/model_mixin.py#L348) where you freeze all weights and then manually "unfreeze" the weights you want to train. This manual freezing then replaces the `train_adapter(_fusion)`method call.
I hope this helps.
