### ISSUE TITLE
Why are the hidden states for each layer the same as the transformer hidden states instead of the language adapter's hidden state?

### ISSUE THREAD

**Issue by ajesujoba** [adapter-hub/adapter-transformers#493]
While trying to check the hidden states before and after the language adapter in XLM-Roberta (using AutoModelForMaskedLM), I found that the output of the language adapter is not the hidden state of the layers, but instead the hidden state of the Transformer model is the hidden states for each layer. 

Below is my code snippet where I checked the output for the Transformer's hidden state and
```
from transformers import AutoAdapterModel
from transformers import AutoTokenizer, AutoModelForMaskedLM

# A simple hook class that returns the input and output of a layer during forward/backward pass
class Hook():
    def __init__(self, module, backward=False):
        if backward==False:
            self.hook = module.register_forward_hook(self.hook_fn)
        else:
            self.hook = module.register_backward_hook(self.hook_fn)
    def hook_fn(self, module, input, output):
        self.input = input
        self.output = output
    def close(self):
        self.hook.remove()

tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")
model = AutoModelForMaskedLM.from_pretrained("xlm-roberta-base")
model.load_adapter("en", model_name = 'xlm-roberta-base')
model.set_active_adapters("en")
```

However, the hidden states from each layer are the same as the output from the Transformer's hidden states.

For example

```
module1 = list(model.get_adapter('en').items())[1][1]  #adapter module output
hook1 = Hook(module1['output_adapter'])
module2=model.roberta.encoder.layer[0].output.LayerNorm # roberta encoder output
hook2 = Hook(module2)

input = tokenizer("Test input", return_tensors="pt")
output = model(**input, output_hidden_states=True)

print("Adapter module output = ", hook1.output[-1])
print("Roberta FFN output = ", hook2.output)
print("encoder hidden state = "output['hidden_states'][1])
```
hook2.output is the same as "output['hidden_states'][1]. Why is this so? Are the transformer hidden states not the input to the language adapters?

**Comment by calpt** [comment]
Hey @ajesujoba,

In general, your assumption that the Transformer's hidden status are the inputs to the adapters is correct.

Your sample code shows the same output because of the specifics of the used adapter config. The "pfeiffer" config used for the lang adapter applies the original layer norm after the adapter module (see `original_ln_after` in https://docs.adapterhub.ml/_images/architecture.png). Thus, if you hook into the layer norm of the Transformer layer, you get the hidden states after forwarding through the adapter. For retrieving the Transformer layer hidden states before the adapter layer, you could e.g. hook into `model.roberta.encoder.layer[0].output.dense`.

(Alternatively, you should also be able to see different hidden states when adding an adapter where `original_ln_after` is set to `False` in the config.)


Hope this clears things up!

**Comment by adapter-hub-bert** [comment]
This issue was closed because it was stale for 14 days without any activity.
