### ISSUE TITLE
 Suggested adapter configuration for transformers with pre-layer normalization

### ISSUE THREAD

**Issue by vasudevgupta7** [Adapter-Hub/adapter-transformers#59]
What is suggested adapter configuration for transformers with pre-layer normalization? I mean where to keep Layer-normalization within adapters?

Thanks

**Comment by JoPfeiff** [comment]
Hi Vasudev,
Could you explain a bit more what you are trying to do? 
I am not sure what exactly you mean with "pre-layer normalization".

**Comment by VasudevGupta7** [comment]
I was trying to fine-tune mbart using language specific adapters. So for that I was writing my own adapters for bart. 
What I meant by Pre-layer normalization is adding layer-normalization before the Feed-forward network and Multi-head attention layer instead of having just like we had in original transformer.
In this scenario, where should I apply layer normalization within adapter? Any suggestions.
