### ISSUE TITLE
Add label information to adapter

### ISSUE THREAD

**Issue by jcklie** [Adapter-Hub/adapter-transformers#63]
# 🚀 Feature request

When I download an adapter, I would like to have something like

```
adapter.get_labels()
adapter.get_labels_dict()
```

so that I do not need to find the right labels in the README and reduce errors when copying them.

Maybe also

```
adapter.get_autoclass()
```

to know whether it is token classification or sequence classification

## Motivation

I want adapters be self-explaining

**Comment by arueckle** [comment]
Makes sense. I think this is more related to the classification head (at least the printing of labels), which makes it a bit more difficult because we support different kinds of heads. Maybe it would be straightforward to add it to https://github.com/Adapter-Hub/adapter-transformers/blob/a30f91242923168de9bb212d830180df7d10dc5a/src/transformers/adapter_bert.py#L620 

We'll have a look!
