### ISSUE TITLE
Upgrade transformers from 1.0.1 to 3.x

### ISSUE THREAD

**Issue by NirantK** [Adapter-Hub/adapter-transformers#69]
# 🚀 Feature request

transformers is now in [3.x version](https://github.com/huggingface/transformers/releases) with cleaner data processing, improved stability and multiple bug fixes

## Motivation
This makes it much easier for making new adapters on custom datasets which are not managed automatically by GLUE scripts. E.g. the `__call__` API from `AutoTokenizer` reduces the separate tokenize, pad, encode, create attention masks steps into single API call.

## Your contribution

If the developers can point out places, e.g. classes or function calls which could act as a starting point for this upgrade - I'd be happy to start a PR. I might need a little help to warm up and get comfortable with the code flow here though.

**Comment by calpt** [comment]
@NirantK  thanks for pointing this out. We try to upgrade to newer versions of Transformers regularly but are a few versions behind currently.

Maybe to clear up the versioning a bit (based on the title of your issue): The version number of adapter-transformers is different from the version number of HuggingFace transformers. Our current release, [v1.0.1](https://github.com/Adapter-Hub/adapter-transformers/releases/tag/adapters1.0.1), is based on Transformers **v2.11.0**.

Since you asked for Transformers 3.x: We have an upgrade to Transformers v3.0.2 ready in #55 which should be working and will be merged shortly. There's also an (unfinished) upgrade to the latest version (v3.3.1) in progress in #72.

**Comment by NirantK** [comment]
Hey @calpt! I understand that v1.0.1 doesn't map to Transformers 1.x. Thanks for the update. 

Looking forward to #72!
