### ISSUE TITLE
ImportError: cannot import name 'AutoModelWithHeads' from 'transformers' 

### ISSUE THREAD

**Issue by rabeehkarimimahabadi** [Adapter-Hub/adapter-transformers#91]
Hi
I am trying with this example colab:
https://colab.research.google.com/github/Adapter-Hub/website/blob/master/app/static/notebooks/Adapter_Quickstart_Training.ipynb#scrollTo=Lbwb3NRf8mBF

getting this error:

```
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    from transformers import AutoTokenizer, EvalPrediction, GlueDataset, GlueDataTrainingArguments, AutoModelWithHeads, AdapterType
ImportError: cannot import name 'AutoModelWithHeads' from 'transformers' (/idiap/user/rkarimi/libs/anaconda3/envs/adapter/lib/python3.7/site-packages/transformers/__init__.py)
```

versions
```
(adapter) rkarimi@italix17:/idiap/user/rkarimi/dev/internship/seq2seq/adapter-transformers$ conda list | grep transformers
adapter-transformers      1.0.1                     <pip>
transformers              3.5.1                     <pip>
(adapter) rkarimi@italix17:/idiap/user/rkarimi/dev/internship/seq2seq/adapter-transformers$ conda list | grep pytorch
pytorch-lightning         1.0.4                     <pip>
adapter hub from github is installed
```

**Comment by JoPfeiff** [comment]
You can't have `transformers` and `adapter-transformers` in your env simultaneously. 
Your code is trying to call `AutoModelWithHeads` which is available in `adapter-transformers`, but not in `transformers`.
Try creating a new env, and your bug should be fixed.

**Comment by rabeehkarimimahabadi** [comment]
Hi
thanks, I need though transformers 3.5.1, this seems to be using
transformers 1.0.1 which is much lower version, how can I have both of
them? shall I reimplement the library if not working with the last version
of transformers? could you give me some pointers please? thanks

**Comment by JoPfeiff** [comment]
The pip `adapter-transformers` 1.0.1 is built on `transformers` 2.11.0  [https://github.com/Adapter-Hub/adapter-transformers/releases/tag/adapters1.0.1]
However, the master branch of `adapter-transformers` is already updated to `transformers` 3.5.1
You can run  `pip install git+https://github.com/Adapter-Hub/adapter-transformers.git` to get that version.

**Comment by rabeehkarimimahabadi** [comment]
I wish the library was just some files adapter implementations, and then
let the people add this to their model, this does not work like this, if I
cannot use latest version of huggingface repo, could you assist me please
what to do ?

**Comment by rabeehkarimimahabadi** [comment]
well, I am realdy doing that, I am using the Adapter-quickstart-training
and this is already doing that¨

**Comment by rabeehkarimimahabadi** [comment]
https://colab.sandbox.google.com/github/Adapter-Hub/website/blob/master/app/static/notebooks/Adapter_Quickstart_Training.ipynb

**Comment by rabeehkarimimahabadi** [comment]
could you direct me which files to reimplement? and give me some
directions, maybe easier if I redo the library for my case, then I am free
to use any versions. thanks

**Comment by JoPfeiff** [comment]
then my first reply is what you need to do.
again, you cannot have `transformers` and `adapter-transformers` in your env simultaneously.
`adapter-transformers` *is* built on `transformers` 3.5.1

**Comment by rabeehkarimimahabadi** [comment]
is this integrated with seq2seq codes? thanks

>

**Comment by rabeehkarimimahabadi** [comment]
As I said I do not have any environment, I am running this colab,
https://colab.sandbox.google.com/github/Adapter-Hub/website/blob/master/app/static/notebooks/Adapter_Quickstart_Training.ipynb,
then if you check version of transformers it is much lower than 3.5.1,
could you point me please where are implementation of adapters, so I just
add them to my codes, without going to the hassel of version issues? thanks

**Comment by JoPfeiff** [comment]
you can find the models which are covered in our [documentation](https://docs.adapterhub.ml/).
we are continuously working on supporting more models.

**Comment by rabeehkarimimahabadi** [comment]
I basically want to use the latest version of transformers, as they update
every day

**Comment by rabeehkarimimahabadi** [comment]
sorry my issue is not resolved, could you run this colab please:
https://colab.sandbox.google.com/github/Adapter-Hub/website/blob/master/app/static/notebooks/Adapter_Quickstart_Training.ipynb
version of transformers is 1, not 3.5, could you give me one example inside
your code implementing adapter for 1 model like BERT, so I learn how the
implementation works to do it for my codes? thanks

**Comment by rabeehkarimimahabadi** [comment]
could you point me please to the minimal implementation details of
adapters?
I would like to use the last huggingface repo version and do not want to
build my codes on top of adapter repo, but just use it with my codes, could
you please assist me how I can implement the adapters, pointing me to the
parts of implementations, thanks

**Comment by calpt** [comment]
Hi @rabeehkarimimahabadi,

I just ran the notebook you linked and didn't get the issue you mentioned. As @JoPfeiff pointed out, if your run
```
pip install git+https://github.com/Adapter-Hub/adapter-transformers.git
```

you get the latest version based on transformers 3.5.1. It will show 1.0.1 in the list of packages because that's our version, **not** Huggingface's version. Basically, it is transformers 3.5.1 although our version is different.

You can merge the latest version of the master branch from Huggingface if you need an even newer version.

For the adapter implementations, please refer to this section in the documentation: https://docs.adapterhub.ml/extending.html or the relevant files in code: https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/adapter_modeling.py, https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/adapter_bert.py.

Hope this helps!

**Comment by rabeehkarimimahabadi** [comment]
Hi,
I need to use it in a custom model, modified from huggingface repo, could
you give me more info how this works with custom models? thanks

**Comment by rabeehkarimimahabadi** [comment]
Hi
thanks for the info, I tried to read these, I found it really hard to
understand which parts are for your work, and which one from hugginggface
repo, to extract those and add to my codes, could you please be
more specific on the part of implementations of adapters?
thanks.
Best regards
Rabeeh

>

**Comment by calpt** [comment]
There's no standard way to integrate adapters into custom models. If our implementations for bert-based models don't work for you, please have a look at our implementation to get an idea how it might be adapted to your needs. Here are the important parts of the implementation:

- [adapter_modeling.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/adapter_modeling.py) implements the single adapter modules
- [adapter_bert.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/adapter_bert.py) integrates the adapter modules into the BERT architecture. Stacking and Fusion of adapters are implemented here. All the integration into the Huggingface model is done via Python mixins. Note how every module of BERT in `modeling_bert.py` has a corresponding mixin here. _When supporting a custom model, you probably want to take this file and make changes to fit your model._
- [adapter_model_mixin.py](https://github.com/Adapter-Hub/adapter-transformers/blob/master/src/transformers/adapter_model_mixin.py) implements useful methods for saving and loading adapters. The classes here are explained in https://docs.adapterhub.ml/extending.html
- in the actual model class (e.g. `modeling_bert.py`), we only implement the mixins. No other changes are done here compared to Huggingface.

Those are all the main classes where our changes are implemented.

Unfortunately, we can't give detailed support for implementing custom models. If your model is part of the Huggingface repo, you can open a feature request so we can potentially support it officially. Otherwise, we can try help out if you have any further specific questions to our implementation.

**Comment by rabeehkarimimahabadi** [comment]
thank you I will look into these. Could you also give me some pointers, if
you have integrated adapters to huggingface seq2seq models? one example of
these would be appreciated to point me out to. thanks

>

**Comment by rabeehkarimimahabadi** [comment]
Hi @calpt  and @JoPfeiff  thanks for all info. I tried to read the pointers, most of the functions are not well-commented, I honestly have difficulty understanding the code base and essential part of adapter layers, I was wondering if any of you have time for a short chat of 15 minutes, I would be greatly thankful for your help. thanks

**Comment by rabeehkarimimahabadi** [comment]
Hi @calpt and @JoPfeiff  I greatly appreciate having a chat with you, I really having a hard time understand how to add the adapter to a custom model, and I greatly appreciate getting more info on this. thanks

**Comment by calpt** [comment]
As the discussion has shifted to #92, closing this thread in favor of #92 to keep discussion in one place.
